# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22faf5fad64c44ff20ed9940851c8ca2f83684944c6c3071b7b8e2225f3dedd92573dfb9f5304b2cd7041746106cf1ac48c4da88b6e322864b332ae61c940660

test:
  secret_key_base: fde30092d96b9a78f5ee53cb67b39ac52a3a48e02cf94ee07d94b051227b76d115d32f7d0abc520f369e978d77d26f34dcf35ddd5831db3824eb8fec8c324221

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
